# Generated by Django 3.1 on 2022-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='python.png', null=True, upload_to='prifile_picture'),
        ),
    ]
